// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;


/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaByb_Xc0x17mt0sEgaAbk52r-0T-yVdw',
    appId: '1:524715143695:web:eb4f4ae97dd0ee9898e97a',
    messagingSenderId: '524715143695',
    projectId: 'proyectolp-e8e1a',
    authDomain: 'proyectolp-e8e1a.firebaseapp.com',
    storageBucket: 'proyectolp-e8e1a.appspot.com',
    measurementId: 'G-2C3DWM7P4J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKFELd_5123WipXYxI69QNvTPUS6iAcwo',
    appId: '1:524715143695:android:8c08f5f9eb290d0298e97a',
    messagingSenderId: '524715143695',
    projectId: 'proyectolp-e8e1a',
    storageBucket: 'proyectolp-e8e1a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCv0kEYAWwJ1EwPFXnDoAP3hqv6DQq0h5E',
    appId: '1:524715143695:ios:18a47a4f35d166fd98e97a',
    messagingSenderId: '524715143695',
    projectId: 'proyectolp-e8e1a',
    storageBucket: 'proyectolp-e8e1a.appspot.com',
    iosClientId: '524715143695-n7rumf2l17ijfbei15knofkng4ho577f.apps.googleusercontent.com',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCv0kEYAWwJ1EwPFXnDoAP3hqv6DQq0h5E',
    appId: '1:524715143695:ios:18a47a4f35d166fd98e97a',
    messagingSenderId: '524715143695',
    projectId: 'proyectolp-e8e1a',
    storageBucket: 'proyectolp-e8e1a.appspot.com',
    iosClientId: '524715143695-n7rumf2l17ijfbei15knofkng4ho577f.apps.googleusercontent.com',
    iosBundleId: 'com.example.login',
  );
}
